apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-hsql
    name: svc-hsql
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-hsql
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-load-balancer-backend
    name: svc-load-balancer-backend
  spec:
    ports:
    - name: "81"
      port: 81
      targetPort: 80
    - name: "444"
      port: 444
      targetPort: 443
    selector:
      io.kompose.service: svc-load-balancer-backend
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-load-balancer-frontend
    name: svc-load-balancer-frontend
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    selector:
      io.kompose.service: svc-load-balancer-frontend
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-platform-admin-init
    name: svc-platform-admin-init
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-platform-admin-init
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-platform-background-processing
    name: svc-platform-background-processing
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-platform-background-processing
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-platform-hac
    name: svc-platform-hac
  spec:
    ports:
    - name: "9111"
      port: 9111
      targetPort: 8088
    selector:
      io.kompose.service: svc-platform-hac
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-platformacceleratorstorefront1
    name: svc-platformacceleratorstorefront1
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-platformacceleratorstorefront1
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-platformacceleratorstorefront2
    name: svc-platformacceleratorstorefront2
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-platformacceleratorstorefront2
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-platformbackoffice1
    name: svc-platformbackoffice1
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-platformbackoffice1
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-platformbackoffice2
    name: svc-platformbackoffice2
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-platformbackoffice2
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-solr
    name: svc-solr
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-solr
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-solrc1
    name: svc-solrc1
  spec:
    ports:
    - name: "8984"
      port: 8984
      targetPort: 8983
    selector:
      io.kompose.service: svc-solrc1
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-solrc2
    name: svc-solrc2
  spec:
    ports:
    - name: "8985"
      port: 8985
      targetPort: 8983
    selector:
      io.kompose.service: svc-solrc2
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-zookeeper1
    name: svc-zookeeper1
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-zookeeper1
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-zookeeper2
    name: svc-zookeeper2
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-zookeeper2
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
    creationTimestamp: null
    labels:
      io.kompose.service: svc-zookeeper3
    name: svc-zookeeper3
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      targetPort: 0
    selector:
      io.kompose.service: svc-zookeeper3
  status:
    loadBalancer: {}
kind: List
metadata: {}
