apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes.yaml
    creationTimestamp: null
    labels:
      io.kompose.service: platform-admin-init
    name: platform-admin-init
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: platform-admin-init
      spec:
        containers:
        - args:
          - admin
          - initialize
          image: gcr.io/gke-hybris-1/b2cacc_deployment_platform
          name: platform-admin-init
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/hybris
            name: platform-admin-init-claim0
          - mountPath: /opt/hybris/data/media
            name: platform-admin-init-claim1
        restartPolicy: Always
        volumes:
        - name: platform-admin-init-claim0
          persistentVolumeClaim:
            claimName: platform-admin-init-claim0
        - name: platform-admin-init-claim1
          persistentVolumeClaim:
            claimName: platform-admin-init-claim1
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes.yaml
    creationTimestamp: null
    labels:
      io.kompose.service: platform-background-processing
    name: platform-background-processing
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: platform-background-processing
      spec:
        containers:
        - args:
          - backgroundProcessing
          image: gcr.io/gke-hybris-1/b2cacc_deployment_platform
          name: platform-background-processing
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/hybris
            name: platform-background-processing-claim0
          - mountPath: /opt/hybris/data/media
            name: platform-background-processing-claim1
        restartPolicy: Always
        volumes:
        - name: platform-background-processing-claim0
          persistentVolumeClaim:
            claimName: platform-background-processing-claim0
        - name: platform-background-processing-claim1
          persistentVolumeClaim:
            claimName: platform-background-processing-claim1
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes.yaml
      kompose.version: 1.7.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: platform-hac
    name: platform-hac
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: platform-hac
      spec:
        containers:
        - args:
          - hac
          image: gcr.io/gke-hybris-1/b2cacc_deployment_platform
          name: platform-hac
          ports:
          - containerPort: 8088
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/hybris
            name: platform-hac-claim0
          - mountPath: /opt/hybris/data/media
            name: platform-hac-claim1
        restartPolicy: Always
        volumes:
        - name: platform-hac-claim0
          persistentVolumeClaim:
            claimName: platform-hac-claim0
        - name: platform-hac-claim1
          persistentVolumeClaim:
            claimName: platform-hac-claim1
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes.yaml
      kompose.version: 1.7.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: platformacceleratorstorefront1
    name: platformacceleratorstorefront1
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: platformacceleratorstorefront1
      spec:
        containers:
        - args:
          - accstorefront
          env:
          - name: JVM_ROUTE
            value: platformacceleratorstorefront1
          image: gcr.io/gke-hybris-1/b2cacc_deployment_platform
          name: platformacceleratorstorefront1
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/hybris
            name: platformacceleratorstorefront1-claim0
          - mountPath: /opt/hybris/data/media
            name: platformacceleratorstorefront1-claim1
        restartPolicy: Always
        volumes:
        - name: platformacceleratorstorefront1-claim0
          persistentVolumeClaim:
            claimName: platformacceleratorstorefront1-claim0
        - name: platformacceleratorstorefront1-claim1
          persistentVolumeClaim:
            claimName: platformacceleratorstorefront1-claim1
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes.yaml
      kompose.version: 1.7.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: platformacceleratorstorefront2
    name: platformacceleratorstorefront2
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: platformacceleratorstorefront2
      spec:
        containers:
        - args:
          - accstorefront
          env:
          - name: JVM_ROUTE
            value: platformacceleratorstorefront2
          image: gcr.io/gke-hybris-1/b2cacc_deployment_platform
          name: platformacceleratorstorefront2
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/hybris
            name: platformacceleratorstorefront2-claim0
          - mountPath: /opt/hybris/data/media
            name: platformacceleratorstorefront2-claim1
        restartPolicy: Always
        volumes:
        - name: platformacceleratorstorefront2-claim0
          persistentVolumeClaim:
            claimName: platformacceleratorstorefront2-claim0
        - name: platformacceleratorstorefront2-claim1
          persistentVolumeClaim:
            claimName: platformacceleratorstorefront2-claim1
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes.yaml
      kompose.version: 1.7.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: platformbackoffice1
    name: platformbackoffice1
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: platformbackoffice1
      spec:
        containers:
        - args:
          - backoffice
          env:
          - name: JVM_ROUTE
            value: platformbackoffice1
          image: gcr.io/gke-hybris-1/b2cacc_deployment_platform
          name: platformbackoffice1
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/hybris
            name: platformbackoffice1-claim0
          - mountPath: /opt/hybris/data/media
            name: platformbackoffice1-claim1
        restartPolicy: Always
        volumes:
        - name: platformbackoffice1-claim0
          persistentVolumeClaim:
            claimName: platformbackoffice1-claim0
        - name: platformbackoffice1-claim1
          persistentVolumeClaim:
            claimName: platformbackoffice1-claim1
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yaml -o kubernetes.yaml
      kompose.version: 1.7.0 (HEAD)
    creationTimestamp: null
    labels:
      io.kompose.service: platformbackoffice2
    name: platformbackoffice2
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: platformbackoffice2
      spec:
        containers:
        - args:
          - backoffice
          env:
          - name: JVM_ROUTE
            value: platformbackoffice2
          image: gcr.io/gke-hybris-1/b2cacc_deployment_platform
          name: platformbackoffice2
          resources: {}
          volumeMounts:
          - mountPath: /etc/ssl/certs/hybris
            name: platformbackoffice2-claim0
          - mountPath: /opt/hybris/data/media
            name: platformbackoffice2-claim1
        restartPolicy: Always
        volumes:
        - name: platformbackoffice2-claim0
          persistentVolumeClaim:
            claimName: platformbackoffice2-claim0
        - name: platformbackoffice2-claim1
          persistentVolumeClaim:
            claimName: platformbackoffice2-claim1
  status: {}

kind: List
metadata: {}