apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: solr
    name: solr
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: solr
      spec:
        containers:
        - args:
          - standard
          image: gcr.io/gke-hybris-1/b2cacc_deployment_solr
          name: solr
          resources: {}
          volumeMounts:
          - mountPath: /opt/solr/server/solr/cores
            name: solr-claim0
        restartPolicy: Always
        volumes:
        - name: solr-claim0
          persistentVolumeClaim:
            claimName: solr-claim0
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: solrc1
    name: solrc1
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: solrc1
      spec:
        containers:
        - args:
          - cloud
          env:
          - name: NODE_DIR
            value: /opt/solr/server
          - name: SOLR_HOST
            value: solrc1
          - name: ZK_HOSTS
            value: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
          image: gcr.io/gke-hybris-1/b2cacc_deployment_solr
          command: ["/bin/sh", "-c", "sleep 10000"]
          name: solrc1
          ports:
          - containerPort: 8983
          resources: {}
          volumeMounts:
          - mountPath: /opt/solr/server/cores
            name: solrc1-claim0
        restartPolicy: Always
        volumes:
        - name: solrc1-claim0
          persistentVolumeClaim:
            claimName: solrc1-claim0
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: solrc2
    name: solrc2
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: solrc2
      spec:
        containers:
        - args:
          - cloud
          env:
          - name: NODE_DIR
            value: /opt/solr/server
          - name: SOLR_HOST
            value: solrc2
          - name: ZK_HOSTS
            value: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
          image: gcr.io/gke-hybris-1/b2cacc_deployment_solr
          name: solrc2
          ports:
          - containerPort: 8983
          resources: {}
          volumeMounts:
          - mountPath: /opt/solr/server/cores
            name: solrc2-claim0
        restartPolicy: Always
        volumes:
        - name: solrc2-claim0
          persistentVolumeClaim:
            claimName: solrc2-claim0
  status: {}
kind: List
metadata: {}
